DEVICE_TYPE = {}
DEVICE_TYPE['control'] = 0x00
DEVICE_TYPE['signal'] = 0x01
DEVICE_TYPE['driver'] = 0x02
DEVICE_TYPE['display'] = 0x03
DEVICE_TYPE['observer'] = 0x04
# DEVICE_TYPE['power'] = 0x05
# DEVICE_TYPE['motion'] = 0x06
DEVICE_TYPE['distance'] = 0x07
# DEVICE_TYPE['communication'] = 0x08
# DEVICE_TYPE['servo'] = 0x09
DEVICE_TYPE['voice'] = 0x0A
# DEVICE_TYPE['wifi'] = 0x0B
DEVICE_TYPE['led'] = 0x0C
# DEVICE_TYPE['button'] = 0x0D
# DEVICE_TYPE['servo'] = 0x0E
# DEVICE_TYPE['buzzer'] = 0x0F
# DEVICE_TYPE['volume'] = 0x10
# DEVICE_TYPE['touch'] = 0x11
DEVICE_TYPE['rfCommunication'] = 0x12
DEVICE_TYPE['hall'] = 0x13
DEVICE_TYPE['acceleration'] = 0x14
DEVICE_TYPE['pulse'] = 0x15
DEVICE_TYPE['rfTelecontroller'] = 0x16
# DEVICE_TYPE['spO2'] = 0x17
# DEVICE_TYPE['color'] = 0x18
# DEVICE_TYPE['thermistor'] = 0x19
# DEVICE_TYPE['bluetooth'] = 0x1A
# DEVICE_TYPE['relay'] = 0x1B
# DEVICE_TYPE['switch'] = 0x1C
# DEVICE_TYPE['stepperMotor'] = 0x1D
# DEVICE_TYPE['subMaster'] = 0x1E
DEVICE_TYPE['ultrasonic'] = 0x1F
# DEVICE_TYPE['dcSpeedMotor'] = 0x20
# DEVICE_TYPE['lineTracer'] = 0x21
DEVICE_TYPE['makeyMakey'] = 0x22
# DEVICE_TYPE['lineTracerPro'] = 0x23
DEVICE_TYPE['ioExtension'] = 0x24
# DEVICE_TYPE['laser'] = 0x25
# DEVICE_TYPE['soilMoisture'] = 0x26
DEVICE_TYPE['pressure'] = 0x27
# DEVICE_TYPE['cameraSwitching'] = 0x28
DEVICE_TYPE['ledTape'] = 0x29
# DEVICE_TYPE['ps2Receiver'] = 0x2A
# DEVICE_TYPE['carButtom'] = 0x2B
# DEVICE_TYPE['voiceBroadcast'] = 0x2C
DEVICE_TYPE['rtc'] = 0x2D
# DEVICE_TYPE['smallStepperMotor'] = 0x2E
DEVICE_TYPE['nfc'] = 0x2F
DEVICE_TYPE['nebulier'] = 0x30
DEVICE_TYPE['buggy'] = 0x31
DEVICE_TYPE['slider'] = 0x32
DEVICE_TYPE['displaymini'] = 0x33
DEVICE_TYPE['climate'] = 0x34
DEVICE_TYPE['light'] = 0x35
DEVICE_TYPE['transmitter'] = 0x36
DEVICE_TYPE['audioPlayer'] = 0x37
DEVICE_TYPE['fingerprint'] = 0x38
DEVICE_TYPE['ledMatrix'] = 0x39
# DEVICE_TYPE['superCar'] = 0x3A
DEVICE_TYPE['multimeter'] = 0x3B
DEVICE_TYPE['pressurePad'] = 0x3C
